stocks_names = {
    "Apple": "AAPL",
    "Microsoft": "MSFT",
    "Amazon": "AMZN",
    "Alphabet": "GOOGL",
    "Tesla": "TSLA",
    "NVIDIA": "NVDA",
    "Berkshire Hathaway": "BRK-A",
    "JPMorgan Chase": "JPM",
    "Johnson & Johnson": "JNJ",
    "Visa": "V",
    "Procter & Gamble": "PG",
    "Mastercard": "MA",
    "Walmart": "WMT",
    "UnitedHealth Group": "UNH",
    "Intel": "INTC",
    "Bank of America": "BAC",
    "Home Depot": "HD",
    "Taiwan Semiconductor": "TSM",
    "Adobe": "ADBE",
    "Netflix": "NFLX",
    "Cisco": "CSCO",
    "Salesforce": "CRM",
    "McDonald's": "MCD",
    "Abbott Laboratories": "ABT",
    "Pfizer": "PFE",
    "Oracle": "ORCL",
    "Coca-Cola": "KO",
    "Adobe": "ADBE",
    "PepsiCo": "PEP",
    "Texas Instruments": "TXN",
    "Caterpillar": "CAT",
    "Merck": "MRK",
    "3M": "MMM",
    "Union Pacific": "UNP",
    "General Electric": "GE",
    "IBM": "IBM",
    "PayPal": "PYPL",
    "Lockheed Martin": "LMT",
    "ExxonMobil": "XOM",
    "Bristol Myers Squibb": "BMY",
    "Raytheon Technologies": "RTX",
    "Lowe's": "LOW",
    "Verizon": "VZ",
    "Accenture": "ACN",
    "T-Mobile": "TMUS",
    "Costco": "COST",
    "CME Group": "CME",
    "Nike": "NKE"
}
